### ISSUE TITLE
Messing with linereturns between groups

### ISSUE THREAD

**Issue by nikaro** [celsiusnarhwal/poetry-sort#2]
Hello,

I'm trying out `poetry-sort` and it looks like it doesn't play well with groups, or something like that.

Here is an example `pyproject.toml` file before:
```toml
[tool.poetry]
name = "test-sort"
version = "0.1.0"
description = ""
authors = ["me <hello@example.com>"]

[tool.poetry.dependencies]
python = "~3.11"
django = "^4.2.0"

[tool.poetry.group.prod]
optional = true

[tool.poetry.group.prod.dependencies]
psycopg = { extras = ["c"], version = "3.1.12" }

[tool.poetry.group.dev.dependencies]
psycopg = { extras = ["binary"], version = "3.1.12" }

[tool.poetry.group.e2e]
optional = true

[tool.poetry.group.e2e.dependencies]
playwright = "1.38.0"

[build-system]
requires = ["poetry-core>=1.2.0"]
build-backend = "poetry.core.masonry.api"
```

And after:
```toml
[tool.poetry]
name = "test-sort"
version = "0.1.0"
description = ""
authors = ["me <hello@example.com>"]

[tool.poetry.dependencies]
python = "~3.11"
django = "^4.2.0"

[tool.poetry.group.prod]
optional = true

[tool.poetry.group.prod.dependencies]
psycopg = { extras = ["c"], version = "3.1.12" }
[tool.poetry.group.dev.dependencies]
psycopg = { extras = ["binary"], version = "3.1.12" }
[tool.poetry.group.e2e]
optional = true

[tool.poetry.group.e2e.dependencies]
playwright = "1.38.0"
[build-system]
requires = ["poetry-core>=1.2.0"]
build-backend = "poetry.core.masonry.api"
```

The diff:
```diff
diff --git a/pyproject.toml b/pyproject.toml
index bebf1dd..44fd880 100644
--- a/pyproject.toml
+++ b/pyproject.toml
@@ -13,16 +13,13 @@ optional = true

 [tool.poetry.group.prod.dependencies]
 psycopg = { extras = ["c"], version = "3.1.12" }
-
 [tool.poetry.group.dev.dependencies]
 psycopg = { extras = ["binary"], version = "3.1.12" }
-
 [tool.poetry.group.e2e]
 optional = true

 [tool.poetry.group.e2e.dependencies]
 playwright = "1.38.0"
-
 [build-system]
 requires = ["poetry-core>=1.2.0"]
 build-backend = "poetry.core.masonry.api"
```
